language: java
cache:
  directories:
  - "$HOME/.m2"
services:
- docker
jobs:
  include:
  - stage: test
  - stage: integration
    before_script:
    - docker run --name blazegraph -d -p 9999:9999 nawer/blazegraph:2.1.1
    - sleep 30
    - wget http://localhost:9999/blazegraph/namespace/kb/sparql
    - mvn package
    - cd engine/target
    - mv endpoints/endpoint-blazegraph.jpar endpoint.jpar
    - java -jar engine-0-SNAPSHOT.jar > log.txt &
    - sleep 30
    - cd ../..
    script:
    - mvn verify
  - stage : deploy
    deploy:
      provider: script
      script: "mvn --settings .travis.settings.xml deploy -X -Dmaven.main.skip -Dmaven.test.skip=true -Drevision=$TRAVIS_TAG"
      skip_cleanup: true
      on:
        tags: true
env:
  global:
    - CI_DEPLOY_USERNAME:
        secure: LOeS8eSq/6qopcdIcWomgbZTLgkUMAfEwPNyJhK8s03R5pF1elZNWTVRawOUXYg/7ygGA/BL3IMVTdh/u6zvgU5n8qW+3Je4gfsWupoPJexDwbGCxAwJj5NNVhslzb+hmKlZuPDGmuKkdvvL04YNkVxBbl+BywUWu0cnrPPWDGyvtKVmx6Vz8LjWQvKbc5GZVmj6NfL05aaJz+FT9Y+hhK2SJ1yipcYRDj/RF3JJ2wjU6QSzzGRuWrKM2Ga26LoerG3s4n9VqRwCEN78wlKb+y7eF54rnZY/nKdQaTTHp0heXVHMhy+oNkybZvaj7MNDPJvh9dVI4k5atnLID1svfPK8f+HwPrRTPRwE1zVMbV686iqKkcVGqCf7WnMj4nHP9e3cNK08g6elfdeF+3fHKWro585ZQq9H3bmmQFWAa8Ib6vsRosEbKKomYjt87zPM452pUBRZGP3kezgn+b1SPU5RhTU3B8cU2b8bFXJ4IhUGy1+GQ3BuzSkxFAH4uPX4vFtXKnxb4tMVqrpfI98krWUYbj2XEzB3uJxhL93fRsDJm4BQaPMS8Wu25obMcB2yG/iBcpn5MqKvxU6o44woBk62PNI+dL8yN7dkHQT05oYJRoqE6H1InQQRMrO+qdGYLuGcD/UXK5XxqhDZylacvfLpoxShpDsqM4ow5Y0jC7M=
    - CI_DEPLOY_PASSWORD:
        secure: D3ecrsaicoVnBILhYrb2YlR9TIGly5zYzPLeUmASFeEJd+z2aB6n6Hr+65BEviDzZ1OntEyTYxQ5TUFy5CicWrjXtEnGu/FFJNC95D9X22SKQLSH4rpAgIPFBVrd2ZJ6EhJaf3SpOyv4BvD61ZvIQUeIuOcKm9HvZXiKTDw3G6ZVUPkEoqnG+Sx7sDS3RKMuIRzclhUS0mkUQqJH/I+AGCR+mFPLiJu1a4cqPEdTTdc6eyKn64Eauqs4ZC5SgTlzTa5/8M5/pYlmDQvi8lItI8vaz21mbCKPZPPW5lBd5c8ssA8UbZDv5zs8AX4CN0S0d7cVCIY5n+onWVG10HrEyHdATECldxfSHUSacoJnGPt64dS9l11MclCHdzdM7q+PkMO1655+YvhBMPMZY5zeI+fOjkWS5WBLlTzG+PybX1QPUuB+raHlQlnpDH4GXeO6hxdGHsTY1vTDJoES0PpFwyQeI1MYTSULu+WLKIlD2coRE/yliZtbANcH7S/WP1tR85tKMHtTi4iw/PbQJGo1NUo3ndRTlGWtIR4b4GpTTtsgeC0QgET30fVzjAh2iGRE5vH/fHa9VDrsC9XVwgbjK6Km3Qq1FGQEy2G0udYxsfGju4Tvw1iveo/lpb5td3SVjy8JTiOn+V2an8bX0GH3Ycup0IYcC0m3s1C+LctC/C0=
